# Generated by Django 3.2.9 on 2021-12-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatt.userchatt'),
        ),
    ]
